CREATE TABLE IF NOT EXISTS Users (
  id INT IDENTITY(1,1) PRIMARY KEY, 
  name NVARCHAR(100) NOT NULL, 
  email NVARCHAR(100) NOT NULL, 
  password NVARCHAR(100) NOT NULL, 
  secretquestion NVARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Camps (
  id INT IDENTITY(1,1) PRIMARY KEY, 
  title NVARCHAR(255) NOT NULL, 
  subtitle NVARCHAR(255) NOT NULL, 
  description NVARCHAR(MAX) NOT NULL, 
  value DECIMAL(18,2) NOT NULL, 
  company NVARCHAR(100) NOT NULL, 
  pix NVARCHAR(100) NOT NULL, 
  userId INT, 
  FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Donations (
  id INT IDENTITY(1,1) PRIMARY KEY, 
  campId INT NOT NULL, 
  userId INT NOT NULL, 
  name NVARCHAR(100) NOT NULL, 
  donate DECIMAL(18,2) NOT NULL,
  FOREIGN KEY (campId) REFERENCES Camps(id),
  FOREIGN KEY (userId) REFERENCES Users(id)
);

CREATE TABLE IF NOT EXISTS CommentsHeroes (
  id INT IDENTITY(1,1) PRIMARY KEY, 
  text NVARCHAR(MAX), 
  userId INT, 
  stars INT, 
  userName NVARCHAR(100), 
  FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Instituicoes (
  id INT IDENTITY(1,1) PRIMARY KEY, 
  name NVARCHAR(100), 
  description NVARCHAR(MAX)
);

CREATE TABLE IF NOT EXISTS Comments (
  id INT IDENTITY(1,1) PRIMARY KEY,
  text NVARCHAR(MAX),
  userId INT,
  userName NVARCHAR(100),
  institutionId INT,
  FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE,
  FOREIGN KEY (institutionId) REFERENCES Instituicoes(id) ON DELETE CASCADE
);
